# Change these first
owner: openfoodfacts # Your GitHub organization or username, where this repository lives
repo: openfoodfacts-upptime # The name of this repository

sites:
  - name: Main website
    url: https://world.openfoodfacts.org
  - name: Hunger Games
    url: https://hunger.openfoodfacts.org/
  - name: .net deployment
    url: https://world.openfoodfacts.net
    headers:
      - "Authorization: Basic b2ZmOm9mZg=="

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /openfoodfacts-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: OpenFoodFacts status
  introTitle: "Status page for OpenFoodFacts infrastructure"
  # introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
