# Change these first
owner: openfoodfacts # Your GitHub organization or username, where this repository lives
repo: openfoodfacts-upptime # The name of this repository

sites:
  - name: Main website (Open Food Facts)
    url: https://world.openfoodfacts.org

  - name: Pro Platform (Open Food Facts)
    url: https://world.pro.openfoodfacts.org

  - name: API v3
    url: https://world.openfoodfacts.org/api/v3/product/3175681257511?fields=product_name,code

  - name: API v2
    url: https://world.openfoodfacts.org/api/v2/product/3175681257511?fields=product_name,code

  - name: Open Food Facts Images
    url: https://images.openfoodfacts.org/images/products/326/385/988/3713/front_fr.19.100.jpg

  - name: Staging deployment
    url: https://world.openfoodfacts.net
    headers:
      - "Authorization: Basic b2ZmOm9mZg=="

  - name: Hunger Games
    url: https://hunger.openfoodfacts.org

  - name: Folksonomy Engine
    url: https://api.folksonomy.openfoodfacts.org

  - name: Blog
    url: https://blog.openfoodfacts.org

  - name: Support platform
    url: https://support.openfoodfacts.org

  - name: Analytics platform
    url: https://analytics.openfoodfacts.org

  - name: Metrics platform
    url: https://metrics.openfoodfacts.org

  - name: Connect platform (Odoo CRM)
    url: https://connect.openfoodfacts.org/

  - name: Monitoring platform
    url: "https://alertmanager.openfoodfacts.org/#/alerts"
    headers:
      - "Authorization: Basic $ALERT_MANAGER_BASICAUTH"

  - name: Search
    url: https://search.openfoodfacts.org/?q=Nutella

  - name: Search (staging)
    url: https://search.openfoodfacts.net/?q=Nutella
    headers:
      - "Authorization: Basic b2ZmOm9mZg=="

  - name: Robotoff
    url: https://robotoff.openfoodfacts.org/api/v1/health

  - name: Nutri-Patrol (production)
    url: https://nutripatrol.openfoodfacts.org

  - name: Knowledge panels for facets (net and org)
    url: https://facets-kp.openfoodfacts.org/render-to-html?facet_tag=categories&value_tag=en:open-beauty-facts&lang_code=en&country=world
    
  - name: Taxonomy editor (pre-prod)
    url: https://ui.taxonomy.openfoodfacts.net/

  - name: Taxonomy editor (prod)
    url: https://ui.taxonomy.openfoodfacts.org/

  - name: Open Prices API
    url: https://prices.openfoodfacts.org/api/v1/status

  - name: Open Prices UI
    url: https://prices.openfoodfacts.org/app

  - name: Open Prices API (pre-prod)
    url: https://prices.openfoodfacts.net/api/v1/status

  - name: Made Near Me
    url: https://madenear.me/

  - name: Emballé près de chez vous
    url: https://cestemballepresdechezvous.fr/

  - name: Combien de Sucres
    url: https://combiendesucres.fr/

  - name: How Much Sugar
    url: https://howmuchsugar.in/

  - name: Wiki
    url: https://wiki.openfoodfacts.org

  - name: Forum
    url: https://forum.openfoodfacts.org

  - name: Open Beauty Facts
    url: https://world.openbeautyfacts.org

  - name: Open Pet Food Facts
    url: https://world.openpetfoodfacts.org

  - name: Open Products Facts
    url: https://world.openproductsfacts.org
    
  - name: Contribalim
    url: https://contribalim.openfoodfacts.org/

  - name: Open Food Facts Query
    url: https://query.openfoodfacts.org/health

  - name: Datasette instance (Mirabelle)
    url: https://mirabelle.openfoodfacts.org/

  - name: Alert Manager
    url: https://alertmanager.openfoodfacts.org/

  - name: Prometheus
    url: https://prometheus.openfoodfacts.org/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.openfoodfacts.org
  # baseUrl: /
  logoUrl: https://static.openfoodfacts.org/images/logos/off-logo-horizontal-light.svg
  name: OpenFoodFacts status
  introTitle: "Status page for OpenFoodFacts infrastructure"
  navbar:
    - title: OpenFoodFacts
      href: https://world.openfoodfacts.org/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
